### ISSUE TITLE
Unclear mention of -Weffc++ in "Use the tools available"

### ISSUE THREAD

**Issue by IgnacioJPickering** [lefticus/cppbestpractices#136]
In the `Use the tools available` section it is recommended to enable the flag `-Wnon-virtual-dtor`, and there is a note that says 
`-Weffc++ warning mode can be too noisy, but if it works for your project, use it also.` however, according to clang's documentation, these two flags are synonyms https://clang.llvm.org/docs/DiagnosticsReference.html#weffc

**Comment by jonvmey** [comment]
GCC's `-Weffc++` flag enables several checks:

> Warn about violations of the following style guidelines from Scott Meyers' Effective C++ series of books:
> *   Define a copy constructor and an assignment operator for classes with dynamically-allocated memory.
> *   Prefer initialization to assignment in constructors.
> *   Have "operator=" return a reference to *this.
> *   Don't try to return a reference when you must return an object.
> *   Distinguish between prefix and postfix forms of increment and decrement operators.
> *   Never overload "&&", "||", or ",".
> 
> This option also enables -Wnon-virtual-dtor, which is also one of the effective C++ recommendations.  However, the check
> is extended to warn about the lack of virtual destructor in accessible non-polymorphic bases classes too.

These are what's being referred to for potentially being "too noisy".

Clang's `-Weffc++` flag by comparison appears to only enable `-Wnon-virtual-dtor` as indicated in the documentation you linked to.

**Comment by IgnacioJPickering** [comment]
Interesting, I didn't check gcc documentation, I usually use clang, I guess the comment makes sense then, there should probably be a clarification that it applies to GCC only but it is not worth keeping the issue open I think.
