### ISSUE TITLE
Addition for section "Avoid Raw Memory Access"

### ISSUE THREAD

**Issue by theta682** [lefticus/cppbestpractices#15]
In section "Avoid Raw Memory Access" using of std::unique_ptr can be added for arrays:

```cpp
auto my_data = std::make_unique<MyDataClass>(128);
```

**Comment by lefticus** [comment]
I don't think that's correct. That would call the `MyDataClass(int)` constructor overload.

**Comment by rob100** [comment]
I think the correct syntax should be something like this:
`auto my_data = std::make_unique<MyDataClass[]>(128);`

But I don't know how this should be added to best practices. What is the use case? When is this method to prefer to using a std::array or a std::vector?

**Comment by lefticus** [comment]
Ok, I did enough research to officially close this issue. See here: http://stackoverflow.com/questions/13061979/shared-ptr-to-an-array-should-it-be-used

`shared_ptr` and `unique_ptr` are not directly designed to work with arrays. You need to provide a custom deleter.

**Comment by theta682** [comment]
Unlike `std::shared_ptr`, `std::unique_ptr` is designed with partial specialization for arrays. It does not need custom deleter. It can be used when C++ code must provide a pointer to an array to C code as a buffer. Using `std::vector` is overkill for such purposes.
For buffers it is better to use something like this `auto buffer = std::make_unique<wchar_t[]>(1024)`.
For arrays of complex classes it is better to use `std::vector` or `std::array`.

**Comment by theta682** [comment]
`std::array` allocates data on stack. This means that it can't have megabytes of data. `std::vector` is too heavy for buffers which don't have to be resized.

**Comment by lefticus** [comment]
Ah, I see the `std::make_unique` overload now.

**Comment by lefticus** [comment]
2nd overload: http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique

**Comment by lefticus** [comment]
Closed with pr #20
