### ISSUE TITLE
Additional motivation i++ vs ++i

### ISSUE THREAD

**Issue by jorenheit** [lefticus/cppbestpractices#19]
Very glad to hear that pre-increment should be preferred. However, your reasons are easily debunked in modern times where compilers will optimize both versions to the same machine level instructions. However, this argument breaks as soon as more complicated types are used: iterators. Your example uses plain old ints, but it would be clearer if you elaborated a little by using (user-defined) classes that overload ++.

**Comment by rob100** [comment]
Even I would not recommend to write your code in a way that relies on optimizations that a compiler should do, I agree that some additional information to this would improve the document.

**Comment by jorenheit** [comment]
I totally agree, yet this is a counter argument I have come across many times. Thanks for your response. I appreciate this initiative!

**Comment by lefticus** [comment]
If either of you has a good example or a good way to re-word this section, please make a pull request for it.
