### ISSUE TITLE
Add abi-compliance-checker to tools section

### ISSUE THREAD

**Issue by cordney** [lefticus/cppbestpractices#33]
I'd like to add the ABI compliance checker (http://ispras.linuxbase.org/index.php/ABI_compliance_checker) to the tools section. It can analyze two library versions and generates a detailed compatibility report regarding API and C++ ABI changes.

I would have opened a MR, but I cannot find a section where this tools fits among the existing ones. Shall I add a new section?

**Comment by lefticus** [comment]
I'd think it would be probably appropriate in the static analysis section underneath the mention of metrix++ 


https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md 

It might make sense to make another subsection for useful tools that don't fall into existing categories (like metrix++)

Jason
