### ISSUE TITLE
"double typically faster than float"

### ISSUE THREAD

**Issue by 983** [lefticus/cppbestpractices#46]
It is stated [here](https://github.com/lefticus/cppbestpractices/blob/master/08-Considering_Performance.md#prefer-double-to-float) that
> Operations on doubles are typically faster than floats.

I can not reproduce this. For my tests, doing math on floats and doubles is equally fast if SSE is not considered. I would even have expected that floats would be faster due to memory bandwidth but I am having trouble testing that since gcc keeps autovectorizing my code.

Anyway, can anyone confirm or deny the statement that doubles are faster than floats anywhere?

**Comment by rob100** [comment]
This is a good summary about "double vs. float":
http://blog2.emptycrate.com/content/double-vs-float-which-better
And a good stackoverflow article with further information regarding the speed:
http://stackoverflow.com/questions/4584637/double-or-float-which-is-faster

**Comment by 983** [comment]
> This is a good summary about "double vs. float":
> http://blog2.emptycrate.com/content/double-vs-float-which-better

The benchmark is just a single measurement and will give different results if run multiple times.
Further, this benchmark is not representative for most real-world programs since they don't operate on the same value in a register, but instead load values from and store them to memory. Since memory is often quoted as a bottleneck, I'd expect floats to win here.
Lastly, the author mentions SSE2, but not that those instructions can operate on twice as many floats as doubles. (I'd like to write more about it, but currently I get an "Error 523" when accessing the website again.)

> And a good stackoverflow article with further information regarding the speed:
> http://stackoverflow.com/questions/4584637/double-or-float-which-is-faster

The accepted answer does not mention SSE and the answers that do come to the conclusion that floats are faster than doubles.

**Comment by lefticus** [comment]
I've updated the discussion with some notes from this issue and links to the stackoverflow discussion
