### ISSUE TITLE
use ? operator

### ISSUE THREAD

**Issue by robertramey** [lefticus/cppbestpractices#6]
```
// Better Idea
const std::string somevalue = [&](){
    if (somecase()) {
      return "Value A";
    } else {
      return "Value B";
    }
  }();

// Better Idea
const std::string somevalue =  somecase()) ? "Value A" :  "Value B";
      return "Value A";
```

**Comment by lefticus** [comment]
That's true for the simple case, but falls apart for more than one choice or more complex choices. I was just trying to keep the example simple.

I'll make an update to it.

**Comment by robertramey** [comment]
const std::string somevalue = 
    somecase() ? 
        "Value A" 
   :  somecase2()  ?
        "Value B"
   :
       "Value C";

I'm just not seeing where using lambda will simplify things.  But I guess it's a matter of taste

**Comment by lefticus** [comment]
I personally think it's a lot more readable to not use the `?:` but regardless, in the tests I've done the compiler is sometimes able to better optimize the lambda version depending on what you are doing. And I've never seen the lambda have worse performance than the nested ternary version

**Comment by vmrob** [comment]
The only time where I've actually used chaining ternary operators was when constexpr required a single return statement:

```C++
constexpr const char* SomeEnumToString(Enum val) {
    return val == kEnumOption1 ? "Option 1" :
           val == kEnumOption2 ? "Option 2" :
           val == kEnumOption3 ? "Option 3" :
           "Invalid Option";
}
```

That's a similar scenario to the one mentioned before, but I think I would still prefer not to rely on that if only for the problems it presents to automatic formatting tools.
