### ISSUE TITLE
t_ and m_ Prefix

### ISSUE THREAD

**Issue by foobar13373** [lefticus/cppbestpractices#72]
I know there is a closed issue about this already. But I want to add a point here against using prefixes like this:

They make the code less readable. You say on the other hand it will be easier to recognize where a variable comes from / what it's scope is (which would be better readability). But this is not the responsibility of code typing style. The responsibility of making the scope / origin of a variable clear is only on the IDE / editors side (syntax highlighting, auto-highlighting selection, outline views and the like).

So, since we nowadays have editors doing all this for you, I'd say prefixing takes a greater amount of readability than it gives, because editors already do provide the positive effects of prefixing so that only the negative aspects of prefixing stay.

**Comment by lefticus** [comment]
You should go ahead and post these thoughts on #11 so that these thoughts are captured for people linking from the doc itself.
