### ISSUE TITLE
No description for /W44640 compiler flag

### ISSUE THREAD

**Issue by Ben1980** [lefticus/cppbestpractices#79]
The MSVC compiler flag /W44640 is not descripted in chapter [MSVC](https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#msvc)

/W4 /W44640 - use these and consider the following

**Comment by Ben1980** [comment]
I think it might refer to /w14640 which is descripted

**Comment by jmarrec** [comment]
@lefticus wiki here needs a sweep too https://github.com/lefticus/cppbestpractices/wiki/Initial-Outline#msvc
