### ISSUE TITLE
Page references?

### ISSUE THREAD

**Issue by aravol** [lefticus/cppbestpractices#9]
To facilitate navigation of this document directly, perhaps we should add "previous" "next" and "Table of Contents" links to the top and bottom of each page?

**Comment by lefticus** [comment]
I don't disagree with you, but I also formatted it to (try) to look good with gitbook. http://lefticus.gitbooks.io/cpp-best-practices/content/ and I'm not sure how well the navigation links would work there?

**Comment by aravol** [comment]
Had never heard of this site. Maybe a link to such on the readme would do well.

**Comment by lefticus** [comment]
It's already there ;)

I could put it in the Preface as well, but the readme doesn't actually make it into the gitbook, and having the Preface reference itself seemed weird. I couldn't decide really where the cppbestpractices.com should point, and how perspective audiences (people wanting to fork it for their own organization vs people who just want to read it) might get to it.

Definitely open to suggestions.

**Comment by claremacrae** [comment]
Just to note, the above URL does not work, and gitbooks.io is now giving 502 Bad gateway

**Comment by claremacrae** [comment]
Ah - I see from the Readme it is now https://www.gitbook.com/book/lefticus/cpp-best-practices
