### ISSUE TITLE
Clean up lefticus' github repositories

### ISSUE THREAD

**Issue by Zyrsha** [lefticus/cppbestpractices#98]
Insofar as "best practices" goes:

When I see lefticus' github repository list, I think this privately:

`*face palm* one of these guys with the crazy disorganized repositories list and a bunch of mixed in random forks of other projects and random postings of small insignificant test projects so that I cannot see the list of projects that he actually created and maintains and I have to scroll through for 10 minutes figuring out what-is-what`

How to alleviate this problem:
1) Create a user called lefticusprivate
2) Move all your junk and test projects and random forks there
3) Leave your serious and significant projects on lefticus.

**Comment by lefticus** [comment]
This is what the "pinned repositories" list is for on github:

https://github.com/lefticus

A suggestion to move cppbestpractices to its own organization might have merit, but I have enough other organizations I'm involved in / manage.
